import re

import requests

from app import *


@app.route("/request", methods=['GET', 'POST'])
def add_request():
    form = WebStatus()
    if form.is_submitted():
        submit_request(request.form)
        return redirect(url_for('add_request'))
    return render_template("requestURL.html", form=form)


# additional functions


def submit_request(result):
    if match(result['url']):
        requests.post(f"https://http-trigger-report.azurewebsites.net/api/http-trigger-report?url={result['url']}"
                      f"&status_code={result['status']}")
    else:
        # TODO: wrong URL
        pass


def create_web_resource_dict(web_resourse_URL, status, time):
    return {'url': web_resourse_URL, 'timestamp': time, 'status': status, 'autoGenerated': False}


def match(url):
    regex = re.compile(
        r'^(?:http|ftp)s?://'  # http:// or https://
        r'(?:(?:[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?\.)+(?:[A-Z]{2,6}\.?|[A-Z0-9-]{2,}\.?)|'  # domain...
        r'localhost|'  # localhost...
        r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'  # ...or ip
        r'(?::\d+)?'  # optional port
        r'(?:/?|[/?]\S+)$', re.IGNORECASE)
    return re.match(regex, url).end() is not None
